# Generated by Django 6.0.1 on 2026-04-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_alter_order_customer_alter_orderitem_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(default="Other", max_length=100),
            preserve_default=False,
        ),
    ]
