# Generated by Django 6.0.1 on 2026-04-28 02:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_product_product_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="address",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="email",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="phone_number",
        ),
    ]
