# Generated by Django 6.0.1 on 2026-04-30 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_remove_customer_address_remove_customer_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.TextField(default="Unknown"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                default="unknown@example.com", max_length=254, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="first_name",
            field=models.CharField(default="Unknown", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="last_name",
            field=models.CharField(default="Unknown", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(default="0000000000", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
